import fs from 'node:fs'
import { PROJECT_DATA_DIRECTORY, projectDataPath } from '../../core/project-storage.js'

/**
 * codegraph 模块加载器（共享）
 *
 * npm SDK 通过 module.exports = require(platformBundle) 转出 CJS 对象。
 * 原生 Node ESM 不一定能推断出命名导出；default 则是整个 CJS exports，
 * CodeGraph 类位于其 CodeGraph 属性中。两种入口均校验实际所需 API。
 */

/** codegraph 实例的最小类型面（避免依赖其内部 .d.ts 的具体形态） */
export interface CgNode {
  id: string
  kind: string
  name: string
  qualifiedName?: string
  filePath: string
  language?: string
  startLine?: number
  endLine?: number
  signature?: string | null
}

export interface CgEdge {
  source: string
  target: string
  kind?: string
  line?: number | null
  column?: number | null
  metadata?: { confidence?: number; resolvedBy?: string; refName?: string }
}

export interface CgInstance {
  searchNodes(query: string, options?: { limit?: number }): Array<{ node: CgNode; score: number }>
  getCallers(nodeId: string, maxDepth?: number): Array<{ node: CgNode; edge: CgEdge }>
  getCallees(nodeId: string, maxDepth?: number): Array<{ node: CgNode; edge: CgEdge }>
  getImpactRadius(nodeId: string, maxDepth?: number): {
    nodes: Map<string, CgNode> | Record<string, CgNode>
    edges: CgEdge[]
    roots: string[]
  }
  getFiles(): Array<{ path: string; language: string; size: number }>
  getStats(): {
    nodeCount: number
    edgeCount: number
    fileCount: number
    nodesByKind?: Record<string, number>
    edgesByKind?: Record<string, number>
    filesByLanguage?: Record<string, number>
    dbSizeBytes?: number
  }
  getIndexState(): 'indexing' | 'complete' | 'partial' | 'failed' | null
  isIndexStale(): boolean
  getLastIndexedAt(): number | null
  /** 全量索引（recreate 后的空实例上调用）；文件锁被占时返回 success:false 而非抛异常 */
  indexAll(options?: {
    onProgress?: (progress: { phase: string; current: number; total: number; currentFile?: string }) => void
  }): Promise<{ success: boolean; errors?: Array<{ message: string; severity: string }> }>
  close(): void
}

export interface CgStatic {
  isInitialized(dir: string): boolean
  openSync(dir: string): CgInstance
  /** 创建 .ae 目录 + codegraph.db 数据库，index:true 时同步完成首次索引（异步方法） */
  init(projectRoot: string, options?: {
    index?: boolean
    onProgress?: (progress: { phase: string; current: number; total: number; currentFile?: string }) => void
  }): Promise<CgInstance>
  /** 删库重建出空实例（只替换 .ae/codegraph.db 及其 WAL/SHM，保留其它项目数据）；要求已初始化（异步方法） */
  recreate(projectRoot: string): Promise<CgInstance>
}

/** Resolve native ESM and CJS namespace shapes without treating the module object as the class. */
export function resolveCodeGraphModule(module: unknown): CgStatic {
  const property = (value: unknown, key: string): unknown =>
    value !== null && (typeof value === 'object' || typeof value === 'function')
      ? Reflect.get(value, key) : undefined
  const candidates = [property(module, 'CodeGraph'), property(property(module, 'default'), 'CodeGraph')]
  const required = ['openSync', 'isInitialized', 'init', 'recreate'] as const
  for (const candidate of candidates) {
    if (candidate && required.every(method => typeof property(candidate, method) === 'function')) {
      return candidate as CgStatic
    }
  }
  throw new Error('代码图组件接口不兼容：缺少 CodeGraph.openSync/isInitialized/init/recreate。请更新配套引擎运行时；无需修改项目或连接令牌。')
}

// The SDK upgrades files bearing its old header, even if custom rules were added.
// Restore only its exact generated bytes so concurrent user edits are never replaced.
const SDK_DEFAULT_GITIGNORE = '# CodeGraph data files — local to each machine, not for committing.\n' +
  '# Ignore everything in .codegraph/ except this file itself, so transient\n' +
  '# files (the database, daemon.pid, sockets, logs) never show up in git.\n*\n!.gitignore\n'

function preserveProjectGitignore(root: string): () => void {
  const ignorePath = projectDataPath(root, '.gitignore')
  let original: Buffer
  try {
    original = fs.readFileSync(ignorePath)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return () => {}
    throw error
  }
  return () => {
    let current: Buffer
    try {
      current = fs.readFileSync(ignorePath)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return
      throw error
    }
    if (!current.equals(original) && current.equals(Buffer.from(SDK_DEFAULT_GITIGNORE))) {
      fs.writeFileSync(ignorePath, original)
    }
  }
}

const storageAdapters = new WeakMap<CgStatic, CgStatic>()

function projectStorageAdapter(sdk: CgStatic): CgStatic {
  const existing = storageAdapters.get(sdk)
  if (existing) return existing
  const adapter: CgStatic = {
    isInitialized: root => sdk.isInitialized(root),
    openSync(root) {
      const restore = preserveProjectGitignore(root)
      try { return sdk.openSync(root) } finally { restore() }
    },
    async init(root, options) {
      const restore = preserveProjectGitignore(root)
      // Restore immediately after library initialization, before a potentially long index.
      const instance = await sdk.init(root, { ...options, index: false }).finally(restore)
      try {
        if (options?.index) {
          const result = await instance.indexAll({ onProgress: options.onProgress })
          if (result.success === false) throw new Error(result.errors?.[0]?.message ?? '创建代码图索引失败')
        }
        return instance
      } catch (error) {
        instance.close()
        throw error
      }
    },
    async recreate(root) {
      const restore = preserveProjectGitignore(root)
      return sdk.recreate(root).finally(restore)
    },
  }
  storageAdapters.set(sdk, adapter)
  return adapter
}

/** Load lazily: an unavailable optional component must not prevent engine startup. */
export async function loadCodeGraph(): Promise<CgStatic> {
  // SDK 只接受单级目录名；保留源码根目录，使用其官方配置将数据库、锁和缓存集中到 .ae。
  // 索引器同时自动排除此目录。所有调用共享固定配置，避免异步索引中途切换存储位置。
  process.env.CODEGRAPH_DIR = PROJECT_DATA_DIRECTORY
  return projectStorageAdapter(resolveCodeGraphModule(await import('@colbymchenry/codegraph')))
}
