import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { MODELS, INITIAL_MODELS, modelFor, modelConfiguration, compactRound, compactPendingState, resourceBody, strictReviews, reviewsPassed, freshParentTests, evaluateRecall, evaluateRetrieval, freezeRequirement, frozenViolations, evidenceMatrix, allPages, independentTest, readEnvelope, modelEvidenceFailure, reviewVerdict } from './continuation-driver.mjs'
const files=[{file:'src/domain.mjs',sha256:'abc',modifiedAtMs:1000}]
const child=(role,extra={})=>({runId:role,description:'review/'+role,status:'succeeded',modelId:'model',startedAt:1100,finishedAt:1300,resultSummary:'pass\nsource:1 valid',...extra})
test('first wave uses three Qwen sessions and rotates all five per session',()=>{assert.deepEqual([1,2,3,4,5].map(index=>modelFor(index,0)),INITIAL_MODELS);assert.equal(INITIAL_MODELS.filter(model=>model==='qwen3.8-flash').length,3);for(let index=1;index<=5;index++)assert.equal(new Set([0,1,2,3,4].map(milestone=>modelFor(index,milestone))).size,5)})
test('retries cross models and continued milestones return to the initial model',()=>{for(let index=1;index<=5;index++){assert.notEqual(modelFor(index,0,1),modelFor(index,0));assert.equal(new Set([0,1,2,3,4].map(attempt=>modelFor(index,0,attempt))).size,5);assert.equal(modelFor(index,5),modelFor(index,0))}})
test('three initial Qwen sessions switch to separate MiniMax GLM and Kimi primary models',()=>assert.deepEqual([1,2,3].map(index=>modelFor(index,1)),['MiniMax-M2.5','glm-5.3','kimi-k2.6']))
test('unobserved provider identity is not incorrectly labelled a model switch',()=>{assert.equal(modelEvidenceFailure({},'qwen'),'actual_model_unobserved');assert.equal(modelEvidenceFailure({actualModelId:'qwen'},'qwen'),null);assert.equal(modelEvidenceFailure({actualModelId:'glm'},'qwen'),'actual_model_mismatch')})
test('durable snapshot observation recovers transient transport without duplicating a mutation',async()=>{let calls=0;const observations=[];const result=await readEnvelope('http://test/snapshot',{}, {fetchImpl:async()=>{if(calls++===0)throw new Error('temporary timeout');return new Response(JSON.stringify({code:200,data:{runId:'durable'}}))},delay:async()=>{},onRetry:row=>observations.push(row)});assert.equal(result.data.runId,'durable');assert.equal(calls,2);assert.equal(observations[0].reason,'transport');calls=0;await assert.rejects(readEnvelope('http://test/chat',{method:'POST'},{fetchImpl:async()=>{calls++;throw new Error('ambiguous accepted POST')},delay:async()=>{}}),/ambiguous/);assert.equal(calls,1)})
test('read retries gateway outages but retains semantic failure and abort boundaries',async()=>{let calls=0;const body={code:200,data:[]};assert.deepEqual(await readEnvelope('http://test/archive',{}, {fetchImpl:async()=>new Response(JSON.stringify(body),{status:calls++===0?503:200}),delay:async()=>{}}),body);assert.equal(calls,2);calls=0;await assert.rejects(readEnvelope('http://test/missing',{}, {fetchImpl:async()=>{calls++;return new Response(JSON.stringify({code:404,message:'missing'}),{status:404})},delay:async()=>{}}));assert.equal(calls,1);const controller=new AbortController();controller.abort();calls=0;await assert.rejects(readEnvelope('http://test/snapshot',{signal:controller.signal},{fetchImpl:async()=>{calls++;throw new Error('aborted')},delay:async()=>{}}));assert.equal(calls,1)})
test('real models API resolved capability shape drives context and thinking',()=>{assert.deepEqual(modelConfiguration({modelId:'qwen',capabilities:{contextWindow:128000,thinking:false},resolvedCapabilities:{contextWindow:100000,thinking:true,toolCalling:true}}),{modelId:'qwen',contextWindow:100000,thinkingMode:'low',capabilities:{contextWindow:100000,thinking:true,toolCalling:true}});assert.equal(modelConfiguration({modelId:'m',capabilities:{contextWindow:100000,thinking:false}}).thinkingMode,false);assert.equal(modelConfiguration({modelId:'m',resolvedCapabilities:{contextWindow:100000}}).contextWindow,100000)})
test('checkpoint round keeps evidence references without growing transcripts',()=>{const round=compactRound({dispatchId:'d',evidenceFile:'/evidence/result.json',success:true,toolEvents:['huge'],prompt:'huge',answer:'huge',verifications:[{stdout:'huge'}]});assert.equal(round.evidenceFile,'/evidence/result.json');assert.equal(round.success,true);for(const key of ['toolEvents','prompt','answer','verifications'])assert.equal(key in round,false)})
test('active checkpoint projection retains running intervals for live overlap accounting',()=>{const pending={dispatchId:'d',runId:'r',stateFile:'/tmp/attempt-state.json',requirementId:'q',attempt:2,status:'running',startedAt:'2026-10-10T00:00:00.000Z',modelId:'qwen3.8-flash',stateIntervals:[{status:'running',from:100,to:200}],prompt:'secret',answer:'large',toolEvents:['large'],item:{id:'q',title:'Q',baseline:{stdout:'large',exitCode:1,testSummary:{tests:1}}}};const compact=compactPendingState(pending);assert.deepEqual(compact.stateIntervals,pending.stateIntervals);assert.equal(compact.status,'running');assert.equal(compact.modelId,pending.modelId);assert.equal('prompt' in compact,false);assert.equal('answer' in compact,false);assert.equal(compact.item.baseline.stdout,undefined)})
test('request-level resource fields use actual ChatBody names',()=>{const body=resourceBody({inlineSkills:[{id:'s'}],inlineMcpServers:[{id:'m'}],knowledgeBaseIds:['kb'],requiredTools:['search_history']},['read_file']);assert.deepEqual(body.knowledgeBases,['kb']);assert.deepEqual(body.skills,['s']);assert.deepEqual(body.mcpServers,['m']);assert.deepEqual(body.allowedTools,['read_file','search_history']);assert.equal('knowledgeBaseIds'in body,false)})
test('machine failed reviewer cannot pass with partial text',()=>assert.equal(reviewsPassed(strictReviews(null,[child('A'),child('B',{status:'failed',partialOutput:'pass',error:{code:'MAX_STEPS'}})],'review/',files)),false))
test('blocking succeeded reviewer cannot pass',()=>assert.equal(reviewsPassed(strictReviews(null,[child('A'),child('B',{resultSummary:'blocking\nbroken'})],'review/',files)),false))
test('actual explicit Markdown and Chinese review verdicts retain machine freshness checks',()=>{for(const summary of ['**pass**\nsource:1','**结论：pass**','基于只读定位完成静态评审：\n\n## 结论：PASS\n证据','我需要先读取文件\n\n**结果：**\npass\n未发现问题']){assert.equal(reviewVerdict(summary),'pass');assert.equal(reviewsPassed(strictReviews(null,[child('A',{resultSummary:summary}),child('B')],'review/',files)),true)}for(const summary of ['tests pass but no review verdict','**blocking**\nbroken','pass\n结论：blocking','## 阻塞： broken'])assert.notEqual(reviewVerdict(summary),'pass');assert.equal(reviewsPassed(strictReviews(null,[child('A',{status:'failed',resultSummary:'**pass**'}),child('B')],'review/',files)),false)})
test('only fresh successful current-source dual reviewers pass',()=>{assert.equal(reviewsPassed(strictReviews(null,[child('A'),child('B')],'review/',files)),true);assert.equal(reviewsPassed(strictReviews(null,[child('A',{startedAt:900}),child('B')],'review/',files)),false);const previous=strictReviews(null,[child('A'),child('B')],'review/',files);assert.equal(reviewsPassed(strictReviews(previous,[],'review/',[{...files[0],sha256:'changed'}])),false)})
test('parent test created before review cannot pass merely by finishing after',()=>{const jobs=[{runId:'root',command:'node',args:['check.mjs'],cwd:process.cwd(),status:'succeeded',exitCode:0,createdAt:1200,finishedAt:1600}];assert.equal(freshParentTests(jobs,'root',process.cwd(),{command:'node',args:['check.mjs']},1300).length,0);jobs[0].createdAt=1301;assert.equal(freshParentTests(jobs,'root',process.cwd(),{command:'node',args:['check.mjs']},1300).length,1);assert.equal(freshParentTests(jobs,'different',process.cwd(),{command:'node',args:['check.mjs']},1300).length,0)})
test('private oracle verifies answer before tools without exposing expected text',()=>{const probes=[{id:'p',expectedPatterns:['DEC-42','37'],forbiddenPatterns:['99']}],answer='[HISTORY_RECALL] {"p":"DEC-42 quota 37"}\n';const result=evaluateRecall(probes,answer,answer.length);assert.equal(result.passed,true);assert.equal(JSON.stringify(result).includes('DEC-42'),false);assert.equal(evaluateRecall(probes,answer,0).passed,false);assert.equal(evaluateRecall(probes,'[HISTORY_RECALL] {"p":"DEC-42 quota 99"}',100).passed,false)})
test('recall rejects missing, multiline malformed or wrong JSON answers',()=>{const probes=[{id:'p',expectedPatterns:['yes']}];for(const answer of ['yes','[HISTORY_RECALL] {bad}','[HISTORY_RECALL] {"other":"yes"}'])assert.equal(evaluateRecall(probes,answer).passed,false)})
test('verified retrieval needs accurate answer and an actually retrieved older source',()=>{const probes=[{id:'p',expectedPatterns:['quota 37']}],answer='[HISTORY_RETRIEVAL] {"p":{"answer":"quota 37","sourceIds":["old"]}}',events=[{toolCall:{name:'search_history',toolCallId:'t'}},{toolResult:{toolCallId:'t',success:true,output:JSON.stringify({messages:[{messageId:'old',content:'quota 37'}]})}}],sources=[{id:'old',text:'original quota 37',createdAt:1000}];assert.equal(evaluateRetrieval(probes,answer,events,sources,2000).passed,true);assert.equal(evaluateRetrieval(probes,answer,[],sources,2000).passed,false);assert.equal(evaluateRetrieval(probes,answer,events,sources,500).passed,false);assert.equal(evaluateRetrieval(probes,answer,events,[{...sources[0],text:'unrelated'}],2000).passed,false)})
test('tools use explicit name identity without weakening archive identity checks',async()=>{assert.equal((await allPages(async()=>({data:[{name:'read_file'}],pagination:{total:1}}),'/tools',100,'name')).total,1);await assert.rejects(allPages(async()=>({data:[{name:'not-a-message'}],pagination:{total:1}}),'/archive'),/identity/)})
test('pagination collects beyond a finite cap and verifies identity completeness',async()=>{const rows=Array.from({length:20501},(_,id)=>({id}));let calls=0;const data=await allPages(async route=>{calls++;const params=new URL('http://test'+route).searchParams,current=Number(params.get('current')),size=Number(params.get('pageSize'));return{data:rows.slice((current-1)*size,current*size),pagination:{total:rows.length}}},'/archive',1000);assert.equal(data.total,20501);assert.equal(data.items.length,20501);assert.equal(calls,21)})
test('pagination rejects duplicates, missing pages and changing totals',async()=>{await assert.rejects(allPages(async()=>({data:[{id:1},{id:1}],pagination:{total:2}}),'/x'),/Duplicate/);let calls=0;await assert.rejects(allPages(async()=>({data:calls++?[{id:2}]:[{id:1}],pagination:{total:calls===1?3:2}}),'/x'),/changed/);calls=0;await assert.rejects(allPages(async()=>({data:calls++?[]:[{id:1}],pagination:{total:2}}),'/x'),/Incomplete/)})
test('freezing rejects mutable replacements and catches later contract tampering',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'continuation-freeze-')),source=path.join(root,'queue'),destination=path.join(root,'frozen');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'contract.md'),'contract');fs.writeFileSync(path.join(source,'check.mjs'),'check');const item={id:'real-feature',roleId:'domain',title:'Feature',contractFile:'contract.md',testFile:'check.mjs'};const frozen=freezeRequirement(item,source,destination);assert.deepEqual(frozenViolations(frozen),[]);fs.writeFileSync(frozen.contractFile,'tampered');assert.deepEqual(frozenViolations(frozen),['contractFile']);assert.throws(()=>freezeRequirement(item,source,destination),/changed/);fs.rmSync(root,{recursive:true,force:true})})
test('freezing rejects path escape and unsafe identities',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'continuation-escape-'));assert.throws(()=>freezeRequirement({id:'../bad',roleId:'r',title:'x'},root,path.join(root,'frozen')),/safe/);assert.throws(()=>freezeRequirement({id:'ok',roleId:'r',title:'x',contractFile:'../escape',testFile:'x'},root,path.join(root,'frozen')),/regular/);fs.rmSync(root,{recursive:true,force:true})})
test('retained audit freezes without inventing a new contract or test',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'continuation-audit-')),frozen=freezeRequirement({id:'retained-role',roleId:'role',title:'Retained',kind:'retained-audit'},root,path.join(root,'frozen'));assert.equal(frozen.contractFile,undefined);assert.deepEqual(frozenViolations(frozen),[]);fs.rmSync(root,{recursive:true,force:true})})
test('tool invocations do not claim qualified semantic coverage',()=>{const matrix=evidenceMatrix([{dispatchId:'d',toolEvents:[{toolCall:{name:'mcp_x',toolCallId:'t'}},{toolResult:{toolCallId:'t',success:true,output:'actual'}}]}],['mcp_x','search_history']);assert.equal(matrix.tools[0].successfulResults,1);assert.equal(matrix.tools[0].qualified,false);assert.equal(matrix.tools[1].invocations,0);assert.equal(matrix.cas.qualified,false)})
test('independent test runner binds exact argv and enforces exact totals with no skips',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'continuation-test-'));const filename=path.join(root,'check.mjs');fs.writeFileSync(filename,"import test from 'node:test';import assert from 'node:assert/strict';test('real',()=>assert.equal(2+2,4));\n");const command={command:'node',args:[filename]},result=await independentTest(root,command,1);assert.equal(result.contractPassed,true);assert.deepEqual(result.command,command);assert.equal(result.cwd,path.resolve(root));assert.equal(result.executable,process.execPath);assert.match(result.stdout,/real/);assert.equal((await independentTest(root,command,2)).contractPassed,false);fs.rmSync(root,{recursive:true,force:true})})
