import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { produce } from './continuation-workload.mjs'

const OPS=`const d=await load('src/domain.mjs');\nconst setup=()=>{let b=d.createBoard({id:'b'});b=d.addTask(b,{id:'a',title:'Alpha',status:'todo',priority:'high',labels:['red'],assignee:'Ada',dueAt:'2026-10-08T12:00:00.000Z'},{now});b=d.addTask(b,{id:'b',title:'Beta',status:'doing',priority:'normal',labels:['blue','red'],assignee:'Bob',dueAt:'2026-10-10T12:00:00.000Z'},{now});b=d.addTask(b,{id:'c',title:'Gamma',status:'done',labels:[],assignee:'',dueAt:null},{now});return b};\n`
const LEDGER=`const d=await load('src/domain.mjs');\nconst product=(id,stock=10,priceCents=250,sku='SKU-'+id)=>({id,sku,name:'Product '+id,priceCents,stock});\nconst setup=()=>d.addProduct(d.addProduct(d.createLedger(),product('a',10),{now}),product('b',4,500),{now});\n`
const cloneChecks=(expression)=>`test('frozen input and nested collections stay unchanged',()=>{const b=deepFreeze(setup()),before=JSON.stringify(b);${expression};assert.equal(JSON.stringify(b),before)});\n`
const readFeature=(roleId,id,title,contract,fixture,checks)=>({roleId,id,title,contract:contract+' All results derive from the real retained project. Preserve original contracts. New functions must validate supplied options, avoid coercion, be browser-compatible and never mutate inputs unless the contract explicitly returns a new mutation.',code:fixture+checks})

export const DOMAIN_BACKLOG=[
readFeature('ops-domain','ops-due-date-report','Due-date triage report',`Export summarizeTaskDueDates(board,{now,includeArchived=false}={}). now must be valid ISO string (default current time), invalid now or nonboolean includeArchived => INVALID_OPTIONS. Ignore done tasks and archived tasks unless includeArchived. Return exactly {overdueIds,dueTodayIds,upcomingIds,undatedIds}; dates classify using UTC calendar day, overdue is date before today's UTC day (not earlier hour today), dueToday same day, upcoming later day. Sort IDs by ID ascending.`,OPS,`
test('actual due dates classify UTC days and completed tasks are excluded',()=>assert.deepEqual(d.summarizeTaskDueDates(setup(),{now}),{overdueIds:['a'],dueTodayIds:[],upcomingIds:['b'],undatedIds:[]}));
test('today is whole UTC day and undated open tasks stay visible',()=>{let b=setup();b=d.updateTask(b,'a',{dueAt:'2026-10-09T00:00:01.000Z'},{now});b=d.addTask(b,{id:'d',title:'Undated',dueAt:null},{now});assert.deepEqual(d.summarizeTaskDueDates(b,{now:'2026-10-09T23:59:59.000Z'}),{overdueIds:[],dueTodayIds:['a'],upcomingIds:['b'],undatedIds:['d']})});
test('archival policy and invalid option errors are explicit',()=>{const b=d.archiveTask(setup(),'a',{now});assert.deepEqual(d.summarizeTaskDueDates(b,{now}).overdueIds,[]);assert.deepEqual(d.summarizeTaskDueDates(b,{now,includeArchived:true}).overdueIds,['a']);for(const options of [{now:'bad'},{now,includeArchived:'yes'}])assert.throws(()=>d.summarizeTaskDueDates(b,options),e=>e.code==='INVALID_OPTIONS')});
${cloneChecks("d.summarizeTaskDueDates(b,{now})")}`),
readFeature('ops-domain','ops-label-statistics','Label usage and board status breakdown',`Export summarizeTaskLabels(board,{includeArchived=false}={}) => rows {label,count,statusCounts:{todo,doing,done},taskIds}. Each task contributes once per distinct label; sorted labels use Unicode codepoint ascending and taskIds use ID ascending. Include done tasks. Exclude archived by default. Validate boolean option as INVALID_OPTIONS.`,OPS,`
test('label counts and each status count are actual',()=>assert.deepEqual(d.summarizeTaskLabels(setup()),[{label:'blue',count:1,statusCounts:{todo:0,doing:1,done:0},taskIds:['b']},{label:'red',count:2,statusCounts:{todo:1,doing:1,done:0},taskIds:['a','b']}]));
test('archived and unlabeled tasks obey inclusion policy',()=>{const b=d.archiveTask(setup(),'b',{now});assert.deepEqual(d.summarizeTaskLabels(b).map(r=>[r.label,r.count]),[['red',1]]);assert.equal(d.summarizeTaskLabels(b,{includeArchived:true}).length,2);assert.deepEqual(d.summarizeTaskLabels(d.createBoard()),[])});
test('option rejection and returned copies are safe',()=>{const b=setup();assert.throws(()=>d.summarizeTaskLabels(b,{includeArchived:1}),e=>e.code==='INVALID_OPTIONS');const rows=d.summarizeTaskLabels(b);rows[0].taskIds.push('fake');assert.deepEqual(d.summarizeTaskLabels(b)[0].taskIds,['b'])});
${cloneChecks('d.summarizeTaskLabels(b)')}`),
readFeature('ops-domain','ops-query-facets','Facets for the currently filtered task result',`Export buildTaskFacets(board,filters={}) => {total,statuses,priorities,assignees,labels}. Each facet array is rows {value,count} sorted by value codepoint ascending. The exact input filters first run through queryTasks; only matching tasks count, label occurrence per task, empty assignee is an explicit value. No zero-count buckets. Results copy arrays.`,OPS,`
test('facets reflect the filtered result rather than the whole board',()=>assert.deepEqual(d.buildTaskFacets(setup(),{labels:['red']}),{total:2,statuses:[{value:'doing',count:1},{value:'todo',count:1}],priorities:[{value:'high',count:1},{value:'normal',count:1}],assignees:[{value:'Ada',count:1},{value:'Bob',count:1}],labels:[{value:'blue',count:1},{value:'red',count:2}]}));
test('zero results and unassigned tasks remain meaningful',()=>{assert.deepEqual(d.buildTaskFacets(setup(),{query:'no match'}),{total:0,statuses:[],priorities:[],assignees:[],labels:[]});assert.deepEqual(d.buildTaskFacets(setup(),{status:'done'}).assignees,[{value:'',count:1}])});
test('query combinations retain original query semantics',()=>{const b=setup();for(const filters of [{status:'doing'},{priority:'high'},{query:'Alpha'},{assignee:'Bob'}])assert.equal(d.buildTaskFacets(b,filters).total,d.queryTasks(b,filters).length)});
${cloneChecks("d.buildTaskFacets(b,{labels:['red']})")}`),
readFeature('ops-domain','ops-board-diff','A reviewable task diff between retained board snapshots',`Export diffTaskBoards(before,after) => {fromRevision,toRevision,addedIds,removedIds,changed:[{id,fields}]}. IDs sort ascending; compare title,description,status,priority,labels (ordered array),assignee,dueAt,archived,createdAt,updatedAt. Changed fields sort alphabetically and only include actual different JSON values. Equal snapshots yield empty changes. Boards must share ID or throw BOARD_ID_MISMATCH. Neither board changes.`,OPS,`
test('real added removed and edited tasks form one precise diff',()=>{const b=setup();let next=d.removeTask(b,'c',{now});next=d.updateTask(next,'a',{title:'Renamed',priority:'urgent'},{now});next=d.addTask(next,{id:'z',title:'New'},{now});const result=d.diffTaskBoards(b,next);assert.deepEqual(result,{fromRevision:b.revision,toRevision:next.revision,addedIds:['z'],removedIds:['c'],changed:[{id:'a',fields:['priority','title']}]})});
test('archive is a real changed field and equal snapshots are empty',()=>{const b=setup();assert.deepEqual(d.diffTaskBoards(b,structuredClone(b)).changed,[]);assert.deepEqual(d.diffTaskBoards(b,d.archiveTask(b,'b',{now})).changed,[{id:'b',fields:['archived']}])});
test('mismatched board identity fails without modifying either snapshot',()=>{const a=setup(),b={...structuredClone(a),id:'other'},before=JSON.stringify([a,b]);assert.throws(()=>d.diffTaskBoards(a,b),e=>e.code==='BOARD_ID_MISMATCH');assert.equal(JSON.stringify([a,b]),before)});
${cloneChecks('d.diffTaskBoards(b,structuredClone(b))')}`),
readFeature('ops-domain','ops-batch-preview','Atomic batch preview before committing a board change',`Export previewTaskBatch(board,commands,options={}) => {board:predicted,fromRevision,toRevision,changeCount,diff}. Use the real applyBatch implementation, including exact error codes, WIP/CAS/idempotency validation, then diffTaskBoards. changeCount equals addedIds.length+removedIds.length+changed.length. Preview is synchronous and must not change original state or consume original idempotency keys; a caller may separately apply the same batch afterward. Returned predicted state deep copies.`,OPS,`
test('preview exactly predicts genuine batch state and one revision',()=>{const b=setup(),commands=[{type:'update',id:'a',patch:{title:'Preview'}}];const actual=d.applyBatch(b,commands,{now}),result=d.previewTaskBatch(b,commands,{now});assert.deepEqual(result.board,actual);assert.equal(result.fromRevision,b.revision);assert.equal(result.toRevision,actual.revision);assert.equal(result.changeCount,1);assert.deepEqual(result.diff,d.diffTaskBoards(b,actual))});
test('invalid later batch command rolls back the preview',()=>{const b=setup(),before=JSON.stringify(b);assert.throws(()=>d.previewTaskBatch(b,[{type:'update',id:'a',patch:{title:'First'}},{type:'update',id:'missing',patch:{title:'Bad'}}],{now}));assert.equal(JSON.stringify(b),before)});
test('preview output edits cannot modify input and CAS errors are preserved',()=>{const b=setup();assert.throws(()=>d.previewTaskBatch(b,[{type:'update',id:'a',patch:{title:'X'}}],{now,expectedRevision:0}),e=>e.code==='REVISION_CONFLICT');const result=d.previewTaskBatch(b,[{type:'update',id:'a',patch:{title:'X'}}],{now});result.board.tasks[0].title='external';assert.equal(b.tasks[0].title,'Alpha')});
${cloneChecks("d.previewTaskBatch(b,[{type:'update',id:'a',patch:{title:'Y'}}],{now})")}`),
readFeature('ops-domain','ops-duplicate-view','Duplicate a saved view while preserving filter isolation',`Export duplicateSavedView(views,id,{newId,name}={}). Resolve existing ID or VIEW_NOT_FOUND, use createSavedView validation for newId/name and duplicate collisions. Append a new record with copied source filters; preserve original order/IDs/names. Missing/invalid parameters INVALID_VIEW, collisions DUPLICATE_VIEW.`,OPS,`
const views=()=>[{id:'one',name:'Original',filters:{labels:['red'],status:'todo'}}];
test('duplicate appends a distinct ID and name with same filters',()=>assert.deepEqual(d.duplicateSavedView(views(),'one',{newId:'two',name:'Copy'}),[...views(),{id:'two',name:'Copy',filters:{labels:['red'],status:'todo'}}]));
test('filter arrays never alias source or caller-owned collection',()=>{const v=views(),result=d.duplicateSavedView(v,'one',{newId:'two',name:'Copy'});result[1].filters.labels.push('blue');assert.deepEqual(v[0].filters.labels,['red']);assert.deepEqual(result[0].filters.labels,['red'])});
test('all existing view and requested identity validation is retained',()=>{assert.throws(()=>d.duplicateSavedView(views(),'missing',{newId:'two',name:'Copy'}),e=>e.code==='VIEW_NOT_FOUND');assert.throws(()=>d.duplicateSavedView(views(),'one',{newId:'one',name:'Copy'}),e=>e.code==='DUPLICATE_VIEW');assert.throws(()=>d.duplicateSavedView(views(),'one',{newId:'bad id',name:'Copy'}),e=>e.code==='INVALID_VIEW')});
test('frozen view collection can be duplicated without mutation',()=>{const v=deepFreeze(views()),before=JSON.stringify(v);d.duplicateSavedView(v,'one',{newId:'two',name:'Copy'});assert.equal(JSON.stringify(v),before)});`),
readFeature('ops-domain','ops-reorder-views','Explicit complete saved-view ordering',`Export reorderSavedViews(views,ids). ids must be a string array listing every existing ID exactly once. Unknown, duplicate, missing ID or invalid collection => INVALID_VIEW. Return full deep copied collection in requested order. Empty collection requires empty ids. Preserve filters and names.`,OPS,`
const views=()=>[{id:'one',name:'One',filters:{labels:['red']}},{id:'two',name:'Two',filters:{}}];
test('permutation preserves full records in requested order',()=>assert.deepEqual(d.reorderSavedViews(views(),['two','one']),[views()[1],views()[0]]));
test('partial duplicate unknown and non-array permutations reject',()=>{for(const ids of [null,['one'],['one','one'],['one','missing']])assert.throws(()=>d.reorderSavedViews(views(),ids),e=>e.code==='INVALID_VIEW')});
test('empty ordering and deep copied nested filters are safe',()=>{assert.deepEqual(d.reorderSavedViews([],[]),[]);const v=views(),out=d.reorderSavedViews(v,['two','one']);out[1].filters.labels.push('x');assert.deepEqual(v[0].filters.labels,['red'])});
test('frozen complete collections retain bytes',()=>{const v=deepFreeze(views()),before=JSON.stringify(v);d.reorderSavedViews(v,['two','one']);assert.equal(JSON.stringify(v),before)});`),
readFeature('ops-domain','ops-assignee-load','Assignee workload by open tasks and priority',`Export summarizeAssigneeLoad(board,{includeArchived=false}={}) => rows {assignee,total,todo,doing,urgent,taskIds}. Only non-done tasks, default excludes archived. Empty assignee is explicit bucket. urgent counts urgent priority only. Sort rows by total descending then assignee codepoint ascending; taskIds ascending. Validate boolean option INVALID_OPTIONS.`,OPS,`
test('open workload derives from tasks and statuses',()=>assert.deepEqual(d.summarizeAssigneeLoad(setup()),[{assignee:'Ada',total:1,todo:1,doing:0,urgent:0,taskIds:['a']},{assignee:'Bob',total:1,todo:0,doing:1,urgent:0,taskIds:['b']}]));
test('unassigned and urgent tasks contribute actual counts',()=>{let b=d.addTask(setup(),{id:'z',title:'Urgent',priority:'urgent',assignee:''},{now});b=d.addTask(b,{id:'y',title:'Second',assignee:'Bob'},{now});const rows=d.summarizeAssigneeLoad(b);assert.equal(rows[0].assignee,'Bob');assert.equal(rows[0].total,2);assert.equal(rows.find(r=>r.assignee==='').urgent,1)});
test('archived option and empty board remain explicit',()=>{const b=d.archiveTask(setup(),'a',{now});assert.equal(d.summarizeAssigneeLoad(b).length,1);assert.equal(d.summarizeAssigneeLoad(b,{includeArchived:true}).length,2);assert.deepEqual(d.summarizeAssigneeLoad(d.createBoard()),[]);assert.throws(()=>d.summarizeAssigneeLoad(b,{includeArchived:1}),e=>e.code==='INVALID_OPTIONS')});
${cloneChecks('d.summarizeAssigneeLoad(b)')}`),
readFeature('ops-domain','ops-task-title-duplicates','Find normalized duplicate task titles',`Export findDuplicateTaskTitles(board,{includeArchived=false}={}) => rows {normalizedTitle,taskIds}. Normalize title by trim, collapse all whitespace to one space, lowercase; include only groups >=2 tasks. Sort normalizedTitle ascending and IDs ascending. Done tasks included. Archive policy and option validation as above. Do not conflate accents or punctuation.`,OPS,`
test('duplicate groups normalize case and whitespace',()=>{let b=d.addTask(setup(),{id:'x',title:'  ALPHA  '},{now});b=d.addTask(b,{id:'y',title:'Alpha'},{now});assert.deepEqual(d.findDuplicateTaskTitles(b),[{normalizedTitle:'alpha',taskIds:['a','x','y']}])});
test('different accents and punctuation are not merged',()=>{let b=d.addTask(setup(),{id:'x',title:'Álpha'},{now});b=d.addTask(b,{id:'y',title:'Alpha!'},{now});assert.deepEqual(d.findDuplicateTaskTitles(b),[])});
test('archived duplicates are explicitly optional',()=>{const b=d.archiveTask(d.addTask(setup(),{id:'x',title:'ALPHA'},{now}),'x',{now});assert.deepEqual(d.findDuplicateTaskTitles(b),[]);assert.equal(d.findDuplicateTaskTitles(b,{includeArchived:true}).length,1);assert.throws(()=>d.findDuplicateTaskTitles(b,{includeArchived:1}),e=>e.code==='INVALID_OPTIONS')});
${cloneChecks('d.findDuplicateTaskTitles(b)')}`),
readFeature('ops-domain','ops-activity-report','Activity report for an explicit revision range',`Export summarizeBoardActivity(board,{afterRevision=0,beforeRevision=board.revision}={}) => {count,byType,taskIds,firstRevision,lastRevision}. Select events after afterRevision exclusive and through beforeRevision inclusive. Both bounds nonnegative safe integers with after<=before<=board.revision else INVALID_OPTIONS. byType sorted rows {type,count}; taskIds unique non-null IDs sorted; absent selected events firstRevision/lastRevision null.`,OPS,`
test('activity range reports real committed events',()=>{const b=setup(),r=d.summarizeBoardActivity(b,{afterRevision:1,beforeRevision:3});assert.deepEqual(r,{count:2,byType:[{type:'addTask',count:2}],taskIds:['b','c'],firstRevision:2,lastRevision:3})});
test('empty range and mixed mutation types are exact',()=>{const b=d.updateTask(setup(),'a',{title:'Changed'},{now});assert.deepEqual(d.summarizeBoardActivity(b,{afterRevision:4}),{count:0,byType:[],taskIds:[],firstRevision:null,lastRevision:null});assert.deepEqual(d.summarizeBoardActivity(b).byType,[{type:'addTask',count:3},{type:'updateTask',count:1}])});
test('invalid revision ranges never coerce',()=>{const b=setup();for(const options of [{afterRevision:-1},{afterRevision:'1'},{beforeRevision:4},{afterRevision:3,beforeRevision:2}])assert.throws(()=>d.summarizeBoardActivity(b,options),e=>e.code==='INVALID_OPTIONS')});
${cloneChecks('d.summarizeBoardActivity(b)')}`),
readFeature('ledger-domain','ledger-expiry-report','Upcoming reservation expiry report',`Export summarizeReservationExpiry(ledger,{now,withinMinutes=60}={}) => {expiredIds,expiringIds,laterIds,heldQuantity}. now valid ISO (default current time), withinMinutes nonnegative safe integer else INVALID_RESERVATION. Only active reservations; expiresAt<=now expired, <=now+window expiring, rest later. Lists ID ascending. heldQuantity sums line quantities for nonexpired active holds, safe-integer overflow INVALID_QUANTITY.`,LEDGER,`
const held=()=>{let b=d.reserveStock(setup(),{id:'soon',lines:[{productId:'a',quantity:2}],expiresAt:'2026-10-09T00:30:00.000Z'},{now});return d.reserveStock(b,{id:'later',lines:[{productId:'b',quantity:1}],expiresAt:'2026-10-10T00:00:00.000Z'},{now})};
test('upcoming and later holds use real expiry instants',()=>assert.deepEqual(d.summarizeReservationExpiry(held(),{now,withinMinutes:60}),{expiredIds:[],expiringIds:['soon'],laterIds:['later'],heldQuantity:3}));
test('exact expiry and released holds are excluded from held quantity',()=>{let b=held();assert.deepEqual(d.summarizeReservationExpiry(b,{now:'2026-10-09T00:30:00.000Z'}).expiredIds,['soon']);b=d.releaseReservation(b,'soon',{now});assert.equal(d.summarizeReservationExpiry(b,{now}).heldQuantity,1)});
test('invalid windows and empty inventory are explicit',()=>{for(const options of [{now:'bad'},{now,withinMinutes:-1},{now,withinMinutes:'60'}])assert.throws(()=>d.summarizeReservationExpiry(setup(),options),e=>e.code==='INVALID_RESERVATION');assert.deepEqual(d.summarizeReservationExpiry(d.createLedger(),{now}),{expiredIds:[],expiringIds:[],laterIds:[],heldQuantity:0})});
test('frozen held state is not changed',()=>{const b=deepFreeze(held()),before=JSON.stringify(b);d.summarizeReservationExpiry(b,{now});assert.equal(JSON.stringify(b),before)});`),
readFeature('ledger-domain','ledger-stock-diff','Physical stock differences between ledger snapshots',`Export diffInventory(before,after) => {fromRevision,toRevision,addedIds,removedIds,changed:[{productId,beforeStock,stock,delta}]}. Compare IDs and physical stock only; prices/names/order metadata do not cause a stock difference. Sort every list by product ID. Safe integer signed delta. Validate both ledgers.`,LEDGER,`
test('physical changes produce exact signed stock deltas',()=>{const b=setup(),next=d.adjustStock(b,'a',-3,{now});assert.deepEqual(d.diffInventory(b,next),{fromRevision:2,toRevision:3,addedIds:[],removedIds:[],changed:[{productId:'a',beforeStock:10,stock:7,delta:-3}]})});
test('product additions and equal stock are distinguished',()=>{const b=setup(),next=d.addProduct(b,product('c',1),{now});assert.deepEqual(d.diffInventory(b,next).addedIds,['c']);assert.deepEqual(d.diffInventory(b,structuredClone(b)).changed,[])});
test('reconciliation differences match actual absolute physical counts',()=>{const b=setup(),next=d.reconcileInventory(b,[{productId:'b',stock:0},{productId:'a',stock:12}],{now});assert.deepEqual(d.diffInventory(b,next).changed,[{productId:'a',beforeStock:10,stock:12,delta:2},{productId:'b',beforeStock:4,stock:0,delta:-4}])});
${cloneChecks('d.diffInventory(b,structuredClone(b))')}`),
readFeature('ledger-domain','ledger-reconcile-preview','Review an atomic inventory reconciliation before committing',`Export previewInventoryReconciliation(ledger,rows,options={}) => {ledger:predicted,diff,fromRevision,toRevision}. Apply genuine reconcileInventory with exact CAS/idempotency/reservation errors, then diffInventory. Original state and operation keys remain unchanged; previewing does not consume original keys. Returned predicted state deep copied.`,LEDGER,`
test('preview exactly predicts actual domain reconciliation',()=>{const b=setup(),rows=[{productId:'a',stock:3}],options={now,expectedRevision:b.revision,idempotencyKey:'preview'};const result=d.previewInventoryReconciliation(b,rows,options);assert.deepEqual(result.ledger,d.reconcileInventory(b,rows,options));assert.deepEqual(result.diff,d.diffInventory(b,result.ledger));assert.equal(result.fromRevision,b.revision);assert.equal(result.toRevision,b.revision+1)});
test('preview preserves invalid row and stale CAS rejection atomically',()=>{const b=setup(),before=JSON.stringify(b);assert.throws(()=>d.previewInventoryReconciliation(b,[{productId:'a',stock:3},{productId:'missing',stock:0}],{now}),e=>e.code==='PRODUCT_NOT_FOUND');assert.throws(()=>d.previewInventoryReconciliation(b,[{productId:'a',stock:3}],{now,expectedRevision:0}),e=>e.code==='REVISION_CONFLICT');assert.equal(JSON.stringify(b),before)});
test('caller edits cannot change original or consume original operation keys',()=>{const b=setup(),rows=[{productId:'a',stock:3}],result=d.previewInventoryReconciliation(b,rows,{now,idempotencyKey:'p'});result.ledger.products[0].stock=100;assert.equal(b.products[0].stock,10);assert.equal(b.idempotency.length,0);assert.equal(d.reconcileInventory(b,rows,{now,idempotencyKey:'p'}).products[0].stock,3)});
${cloneChecks("d.previewInventoryReconciliation(b,[{productId:'a',stock:3}],{now})")}`),
readFeature('ledger-domain','ledger-order-line-report','Order line quantities and revenue by product',`Export summarizeOrderProducts(ledger,{status='fulfilled'}={}) => rows {productId,sku,quantity,grossCents,refundedQuantity,refundCents,netCents}. status one of placed,fulfilled,cancelled,partially_refunded,refunded,all else INVALID_ORDER. The fulfilled filter includes fulfilled/partially_refunded/refunded orders as the same sales family. Use order line price snapshots, not current product price. Sum matching order lines and matching refund lines, safe integer totals with INVALID_QUANTITY. Sort productId. Do not include products absent matching orders.`,LEDGER,`
const sold=()=>{let b=d.placeOrder(setup(),{id:'order',lines:[{productId:'a',quantity:2},{productId:'b',quantity:1}]},{now});return d.fulfilOrder(b,'order',{now})};
test('fulfilled report uses actual price snapshots and exact line quantities',()=>assert.deepEqual(d.summarizeOrderProducts(sold()),[{productId:'a',sku:'SKU-a',quantity:2,grossCents:500,refundedQuantity:0,refundCents:0,netCents:500},{productId:'b',sku:'SKU-b',quantity:1,grossCents:500,refundedQuantity:0,refundCents:0,netCents:500}]));
test('refund totals reduce net without erasing gross sales',()=>{const b=d.refundOrder(sold(),'order',{id:'r',lines:[{productId:'a',quantity:1}]},{now});assert.deepEqual(d.summarizeOrderProducts(b)[0],{productId:'a',sku:'SKU-a',quantity:2,grossCents:500,refundedQuantity:1,refundCents:250,netCents:250})});
test('status filter and invalid status are retained',()=>{const b=d.placeOrder(setup(),{id:'pending',lines:[{productId:'a',quantity:1}]},{now});assert.deepEqual(d.summarizeOrderProducts(b),[]);assert.equal(d.summarizeOrderProducts(b,{status:'placed'})[0].quantity,1);assert.throws(()=>d.summarizeOrderProducts(b,{status:'invalid'}),e=>e.code==='INVALID_ORDER')});
test('frozen orders refunds and products never change',()=>{const b=deepFreeze(sold()),before=JSON.stringify(b);d.summarizeOrderProducts(b);assert.equal(JSON.stringify(b),before)});`),
readFeature('ledger-domain','ledger-restock-plan','Deterministic reorder quantities from availability',`Export buildRestockPlan(ledger,{targetStock,now}={}) => {revision,targetStock,totalQuantity,rows:[{productId,sku,available,quantity}]}. targetStock required nonnegative safe integer else INVALID_QUANTITY. Use summarizeInventoryHealth availability at now; include only available<targetStock, quantity=targetStock-available; rows sorted SKU. Safe sums. Pure recommendation, no inventory commit.`,LEDGER,`
test('reorder plan fills actual availability to target',()=>assert.deepEqual(d.buildRestockPlan(setup(),{targetStock:6,now}),{revision:2,targetStock:6,totalQuantity:2,rows:[{productId:'b',sku:'SKU-b',available:4,quantity:2}]}));
test('reservations affect recommendations but physical inventory remains unchanged',()=>{const b=d.reserveStock(setup(),{id:'h',lines:[{productId:'a',quantity:8}],expiresAt:'2026-10-10T00:00:00.000Z'},{now});const r=d.buildRestockPlan(b,{targetStock:6,now});assert.equal(r.totalQuantity,6);assert.deepEqual(r.rows.map(row=>[row.productId,row.quantity]),[['a',4],['b',2]]);assert.equal(b.products[0].stock,10)});
test('no changes when target met and invalid targets never coerce',()=>{assert.deepEqual(d.buildRestockPlan(setup(),{targetStock:0,now}).rows,[]);for(const targetStock of [undefined,-1,1.5,'4',Infinity])assert.throws(()=>d.buildRestockPlan(setup(),{targetStock,now}),e=>e.code==='INVALID_QUANTITY')});
${cloneChecks('d.buildRestockPlan(b,{targetStock:20,now})')}`),
readFeature('ledger-domain','ledger-daily-sales','UTC daily fulfilled sales with refund totals',`Export summarizeDailySales(ledger) => rows {date,orderCount,grossCents,refundCents,netCents}. Include fulfilled/partially_refunded/refunded orders. Group by UTC date of the real fulfilOrder audit event (entityId=order.id); legacy lacking that event falls back to order.updatedAt. Include refunds in their original sale-day bucket, not refund-day bucket. Cancelled/placed orders excluded. Sort date ascending. Values integer cents and safe sums.`,LEDGER,`
const sold=()=>{let b=d.placeOrder(setup(),{id:'one',lines:[{productId:'a',quantity:2}]},{now});b=d.fulfilOrder(b,'one',{now});return b};
test('fulfilled order is counted on actual UTC sale date',()=>assert.deepEqual(d.summarizeDailySales(sold()),[{date:'2026-10-09',orderCount:1,grossCents:500,refundCents:0,netCents:500}]));
test('refund on a later date reduces the original sale bucket',()=>{const b=d.refundOrder(sold(),'one',{id:'r',lines:[{productId:'a',quantity:1}]},{now:'2026-10-10T00:00:00.000Z'});assert.deepEqual(d.summarizeDailySales(b),[{date:'2026-10-09',orderCount:1,grossCents:500,refundCents:250,netCents:250}])});
test('pending canceled and no orders produce no fulfilled daily buckets',()=>{const b=d.placeOrder(setup(),{id:'p',lines:[{productId:'a',quantity:1}]},{now});assert.deepEqual(d.summarizeDailySales(b),[]);assert.deepEqual(d.summarizeDailySales(d.cancelOrder(b,'p',{now})),[])});
test('frozen full ledger remains identical',()=>{const b=deepFreeze(sold()),before=JSON.stringify(b);d.summarizeDailySales(b);assert.equal(JSON.stringify(b),before)});`),
readFeature('ledger-domain','ledger-refundable-report','Remaining refundable quantities by fulfilled order',`Export listRefundableOrders(ledger) => rows {orderId,remainingQuantity,remainingCents,lines:[{productId,quantity,priceCents}]}. Include fulfilled/partially_refunded orders with at least one unrefunded unit. Subtract all existing refund quantities by product from original lines; omit zero remaining lines; sort rows orderId and lines productId. Use price snapshots. Never issue a refund or alter stock.`,LEDGER,`
const sold=()=>d.fulfilOrder(d.placeOrder(setup(),{id:'one',lines:[{productId:'a',quantity:2},{productId:'b',quantity:1}]},{now}),'one',{now});
test('report lists the actual remaining refundable price snapshots',()=>assert.deepEqual(d.listRefundableOrders(sold()),[{orderId:'one',remainingQuantity:3,remainingCents:1000,lines:[{productId:'a',quantity:2,priceCents:250},{productId:'b',quantity:1,priceCents:500}]}]));
test('partial refund subtracts units and a complete refund removes the order',()=>{let b=d.refundOrder(sold(),'one',{id:'r',lines:[{productId:'a',quantity:1}]},{now});assert.equal(d.listRefundableOrders(b)[0].remainingQuantity,2);b=d.refundOrder(b,'one',{id:'r2',lines:[{productId:'a',quantity:1},{productId:'b',quantity:1}]},{now});assert.deepEqual(d.listRefundableOrders(b),[])});
test('unfulfilled orders have no refundable exposure',()=>assert.deepEqual(d.listRefundableOrders(d.placeOrder(setup(),{id:'p',lines:[{productId:'a',quantity:1}]},{now})),[]));
test('frozen completed order state remains unchanged',()=>{const b=deepFreeze(sold()),before=JSON.stringify(b);d.listRefundableOrders(b);assert.equal(JSON.stringify(b),before)});`),
readFeature('ledger-domain','ledger-catalog-diff','Catalogue comparison by normalized SKU',`Export compareProductCatalogs(before,after) => {addedSkus,removedSkus,changed:[{sku,fields}]}. Compare normalized original SKU values according to getProductBySku (case insensitive, trim). Changes only name,priceCents,stock; ID changes alone do not change a catalogue row. Sort SKUs lexical uppercase and fields alphabetically. Validate ledgers; no input mutation.`,LEDGER,`
test('catalogue addition and changed physical fields are distinct',()=>{const b=setup();let after=d.addProduct(b,product('c',2,100),{now});after=d.adjustStock(after,'a',1,{now});assert.deepEqual(d.compareProductCatalogs(b,after),{addedSkus:['SKU-C'],removedSkus:[],changed:[{sku:'SKU-A',fields:['stock']}]})});
test('changing name and cents is detected without price coercion',()=>{const b=setup(),after=structuredClone(b);after.products[0].name='New name';after.products[0].priceCents=300;assert.deepEqual(d.compareProductCatalogs(b,after).changed,[{sku:'SKU-A',fields:['name','priceCents']}] )});
test('equal JSON snapshots have no catalogue differences',()=>assert.deepEqual(d.compareProductCatalogs(setup(),structuredClone(setup())),{addedSkus:[],removedSkus:[],changed:[]}));
${cloneChecks('d.compareProductCatalogs(b,structuredClone(b))')}`),
readFeature('ledger-domain','ledger-order-status-report','Status metrics from real order lifecycle state',`Export summarizeOrderStatuses(ledger) => {placed,fulfilled,cancelled,partially_refunded,refunded,total,byStatus:[{status,count,totalCents}]}. byStatus always ordered placed,fulfilled,cancelled,partially_refunded,refunded including zero buckets. Order totalCents uses original line snapshot total even after refunds. Validate ledger and safe sums.`,LEDGER,`
test('order lifecycle metrics reflect actual status transitions',()=>{let b=d.placeOrder(setup(),{id:'p',lines:[{productId:'a',quantity:1}]},{now});b=d.placeOrder(b,{id:'f',lines:[{productId:'b',quantity:1}]},{now});b=d.fulfilOrder(b,'f',{now});assert.deepEqual(d.summarizeOrderStatuses(b),{placed:1,fulfilled:1,cancelled:0,partially_refunded:0,refunded:0,total:2,byStatus:[{status:'placed',count:1,totalCents:250},{status:'fulfilled',count:1,totalCents:500},{status:'cancelled',count:0,totalCents:0},{status:'partially_refunded',count:0,totalCents:0},{status:'refunded',count:0,totalCents:0}]})});
test('cancellation moves a bucket and empty totals stay exact',()=>{const b=d.cancelOrder(d.placeOrder(setup(),{id:'p',lines:[{productId:'a',quantity:1}]},{now}),'p',{now});assert.equal(d.summarizeOrderStatuses(b).cancelled,1);assert.equal(d.summarizeOrderStatuses(d.createLedger()).total,0)});
test('refunds do not rewrite gross order totals',()=>{let b=d.fulfilOrder(d.placeOrder(setup(),{id:'f',lines:[{productId:'a',quantity:2}]},{now}),'f',{now});b=d.refundOrder(b,'f',{id:'r',lines:[{productId:'a',quantity:1}]},{now});assert.equal(d.summarizeOrderStatuses(b).byStatus.find(row=>row.status==='partially_refunded').totalCents,500)});
${cloneChecks('d.summarizeOrderStatuses(b)')}`),
readFeature('ledger-domain','ledger-checkout-preview','Atomic checkout preview with the real stock and pricing rules',`Export previewOrder(ledger,input,options={}) => {ledger:predicted,order,totalCents,stockChanges}. Use genuine placeOrder and return copied created order by input.id, stockChanges diffInventory(before,predicted). Retain exact invalid order/stock/CAS/idempotency behavior and never consume original stock or keys. For existing idempotent replay, return matching actual order and unchanged stockChanges.`,LEDGER,`
test('preview predicts genuine order and stock changes',()=>{const b=setup(),input={id:'preview',lines:[{productId:'a',quantity:2}]},result=d.previewOrder(b,input,{now});const next=d.placeOrder(b,input,{now});assert.deepEqual(result.ledger,next);assert.deepEqual(result.order,next.orders.find(o=>o.id==='preview'));assert.equal(result.totalCents,500);assert.deepEqual(result.stockChanges,d.diffInventory(b,next))});
test('oversell and stale revision fail without touching source',()=>{const b=setup(),before=JSON.stringify(b);assert.throws(()=>d.previewOrder(b,{id:'bad',lines:[{productId:'a',quantity:11}]},{now}),e=>e.code==='INSUFFICIENT_STOCK');assert.throws(()=>d.previewOrder(b,{id:'bad',lines:[{productId:'a',quantity:1}]},{now,expectedRevision:0}),e=>e.code==='REVISION_CONFLICT');assert.equal(JSON.stringify(b),before)});
test('returned order does not alias predicted ledger or original request',()=>{const b=setup(),input={id:'p',lines:[{productId:'a',quantity:1}]},result=d.previewOrder(b,input,{now});result.order.lines[0].quantity=100;assert.equal(result.ledger.orders[0].lines[0].quantity,1);assert.equal(input.lines[0].quantity,1)});
${cloneChecks("d.previewOrder(b,{id:'p',lines:[{productId:'a',quantity:1}]},{now})")}`)
]

// Each dossier is a real input review matrix with distinct board/stock cases,
// operational rationale and boundary policy. It is part of the user requirement,
// not repeated text or a duration filler; later exact archive search can recover it.
export function designDossier(item) {
  const rows=[]
  for(let index=0;index<96;index++) {
    const n=index+1,status=['todo','doing','done'][index%3],stock=(index*17)%101,reserved=Math.min(stock,index%13),quantity=index%9+1
    rows.push({caseId:item.id+'-case-'+String(n).padStart(3,'0'),customer:['North depot','Coastal operations','Research queue','Returns desk'][index%4],task:{id:'task-'+n,title:['Urgent outbound inspection','Follow up missing proof','Review return authorization','Check reserved units'][index%4]+' '+n,status,priority:['low','normal','high','urgent'][index%4],labels:['site-'+index%7,'wave-'+index%5],assignee:['Ada','Bob','Chen',''][index%4],archived:index%11===0},inventory:{productId:'product-'+n,sku:'SITE-'+index%7+'-ITEM-'+n,physicalStock:stock,reserved,available:stock-reserved,priceCents:quantity*125,orderQuantity:quantity},review:{identity:'Preserve supplied IDs and compare only contracted fields; a reordered input cannot silently change a canonical output.',isolation:'This case belongs to the current session and original project. The other project and differently named storage keys must remain unchanged.',failurePolicy:index%3===0?'Validate every later row before committing anything; malformed suffix does not authorize a partial prefix.':index%3===1?'A stale expected version/revision must visibly conflict; no hidden overwrite or guessed success.':'Copies returned to the caller must not alias nested input labels, filters, lines or saved records.',displayPolicy:'User supplied Unicode and HTML-like names are literal data; readable labels, stable order and truthful totals are required.',historicalConstraint:'Continue from the retained R4 implementation and keep its source API and all previously accepted milestones.'}})
  }
  return '\n\nDesign review input for '+item.id+'; evaluate these distinct operational scenarios using this milestone contract. The matrix informs implementation and independent review; it does not authorize extra APIs beyond the contract.\n'+rows.map(row=>JSON.stringify(row)).join('\n')
}

export function appendBacklog(root,items=DOMAIN_BACKLOG) {
  const designDirectory=path.join(path.resolve(root),'requirements','design-inputs');fs.mkdirSync(designDirectory,{recursive:true})
  const prepared=items.map(item=>{const designInputFile=path.join('design-inputs',item.id+'.txt');fs.writeFileSync(path.join(path.resolve(root),'requirements',designInputFile),designDossier(item));return {...item,contract:item.contract,code:item.code,prompt:item.contract,designInputFile}})
  const result=produce(root,prepared)
  const queueFile=path.join(path.resolve(root),'requirements','queue.json'),queue=JSON.parse(fs.readFileSync(queueFile,'utf8')),byId=new Map(prepared.map(item=>[item.id,item]))
  for(const item of queue.requirements){const source=byId.get(item.id),designInputFile=path.join('design-inputs',item.id+'.txt'),absolute=path.join(path.dirname(queueFile),designInputFile);if(!fs.existsSync(absolute))fs.writeFileSync(absolute,designDossier(item));if(source&&!fs.existsSync(path.join(path.dirname(queueFile),'frozen',item.id))){item.prompt=source.prompt;item.designInputFile=source.designInputFile}else if(fs.existsSync(absolute)&&!fs.existsSync(path.join(path.dirname(queueFile),'frozen',item.id)))item.designInputFile=designInputFile}
  fs.writeFileSync(queueFile,JSON.stringify(queue,null,2)+'\n');return result
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){if(!process.argv[2])throw new Error('Usage: node continuation-backlog.mjs CONTINUATION_RUN_ROOT');console.log(JSON.stringify(appendBacklog(process.argv[2])))}
